<?php

/**
 * Service Test Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - heading (text)
 * - subtitle (textarea)
 * - description (wysiwyg)
 */

$heading = get_sub_field('heading') ?: '';
$subtitle = get_sub_field('subtitle') ?: '';
$description = get_sub_field('description') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($heading || $subtitle || $description)): ?>
  <section class="service_test py-12">
    <div class="container-fluid">

      <?php if ($subtitle || $description): ?>
        <div class="section-heading text-center">
          <?php if ($subtitle): ?>
            <h2 class="fade-text"><?= esc_html($subtitle); ?></h2>
          <?php endif; ?>
          <?php if ($description): ?>
            <div class="anim-uni-in-up"><?= wp_kses_post($description); ?></div>
          <?php endif; ?>
        </div>
      <?php endif; ?>

      <?php if ($heading): ?>
        <h2 class="fade-text"><?= esc_html($heading); ?></h2>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
