<?php

/**
 * Service Test Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - section_title (text)
 * - section_description (wysiwyg)
 */

$section_title = get_sub_field('section_title') ?: '';
$section_description = get_sub_field('section_description') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($section_title || $section_description)): ?>
  <section class="service_test_block py-12">
    <div class="container-fluid">

      <?php if ($section_title): ?>
        <h2 class="fade-text"><?= esc_html($section_title); ?></h2>
      <?php endif; ?>

      <?php if ($section_description): ?>
        <div class="anim-uni-in-up">
          <?= wp_kses_post($section_description); ?>
        </div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
