<?php

/**
 * Service Block Css Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (text)
 * - service_block_css_item (repeater)
 *   - title (text)
 */

$title = get_sub_field('title') ?: '';
$service_block_css_item = get_sub_field('service_block_css_item') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $service_block_css_item)): ?>
  <section class="service_block_css py-12">
    <div class="container-fluid">

      <?php if ($title): ?>
        <div class="section-heading text-center">
          <?php if ($title): ?>
            <h2 class="fade-text"><?= esc_html($title); ?></h2>
          <?php endif; ?>
        </div>
      <?php endif; ?>

      <?php if ($service_block_css_item): ?>
        <div class="service_block_css_item-grid">
          <?php foreach ($service_block_css_item as $item): ?>
            <div class="service_block_css_item-item">
              <?php if ($item['title']): ?>
                <div class="title"><?= esc_html($item['title']); ?></div>
              <?php endif; ?>
            </div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
