<?php

/**
 * Service List Items Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - service_items (repeater)
 *   - service_img (image)
 *   - title (text)
 *   - content (wysiwyg)
 */

$service_items = get_sub_field('service_items') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($service_items)): ?>
  <section class="service_list_items py-12">
    <div class="container mx-auto px-4">

      <?php if ($service_items): ?>
        <div class="service_items-grid">
          <?php foreach ($service_items as $item): ?>
            <div class="service_items-item">
              <?php if ($item['service_img']): ?>
                <img src="<?php echo esc_url($item['service_img']['url']); ?>" alt="<?php echo esc_attr($item['service_img']['alt']); ?>">
              <?php endif; ?>
              <?php if ($item['title']): ?>
                <div class="title"><?php echo esc_html($item['title']); ?></div>
              <?php endif; ?>
              <?php if ($item['content']): ?>
                <div class="content"><?php echo esc_html($item['content']); ?></div>
              <?php endif; ?>
            </div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
