<?php

/**
 * Service Page Test Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - title (text)
 * - content (wysiwyg)
 */

$title = get_sub_field('title') ?: '';
$content = get_sub_field('content') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $content)): ?>
  <section class="service_page_test_block py-12">
    <div class="container mx-auto px-4">

      <?php if ($title): ?>
        <h2 class="text-3xl font-bold mb-6"><?php echo esc_html($title); ?></h2>
      <?php endif; ?>

      <?php if ($content): ?>
        <div class="content-content prose max-w-none">
          <?php echo wp_kses_post($content); ?>
        </div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
