<?php

/**
 * Service List Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - title (text)
 */

$title = get_sub_field('title') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title)): ?>
  <section class="service_list_block py-12" data-component="ServiceListBlock">
    <div class="container-fluid">

      <?php if ($title): ?>
        <div class="section-heading text-center">
          <?php if ($title): ?>
            <h2 class="fade-text"><?= esc_html($title); ?></h2>
          <?php endif; ?>
        </div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
