<?php

/**
 * News Listing Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - section_title (text)
 * - posts_per_page (number)
 * - show_filters (true_false)
 * - show_search (true_false)
 */

$section_title = get_sub_field('section_title') ?: '';
$posts_per_page = get_sub_field('posts_per_page') ?: '';
$show_filters = get_sub_field('show_filters') ?: '';
$show_search = get_sub_field('show_search') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($section_title || $posts_per_page || $show_filters)): ?>
  <section class="news_listing_block py-12">
    <div class="container mx-auto px-4">

      <?php if ($section_title): ?>
        <h2 class="text-3xl font-bold mb-6"><?php echo esc_html($section_title); ?></h2>
      <?php endif; ?>

      <?php if ($posts_per_page): ?>
        <div class="posts_per_page-field"><?php echo esc_html($posts_per_page); ?></div>
      <?php endif; ?>

      <?php if ($show_filters): ?>
        <div class="show_filters-field"><?php echo esc_html($show_filters); ?></div>
      <?php endif; ?>

      <?php if ($show_search): ?>
        <div class="show_search-field"><?php echo esc_html($show_search); ?></div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
