<?php

/**
 * Content Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - content_type (select)
 * - title (text)
 * - subtitle (text)
 * - content (wysiwyg)
 * - image (image)
 * - gallery_images (gallery)
 * - background_color (select)
 */

$content_type = get_sub_field('content_type') ?: '';
$title = get_sub_field('title') ?: '';
$subtitle = get_sub_field('subtitle') ?: '';
$content = get_sub_field('content') ?: '';
$image = get_sub_field('image') ?: '';
$gallery_images = get_sub_field('gallery_images') ?: '';
$background_color = get_sub_field('background_color') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($content_type || $title || $subtitle)): ?>
  <section class="news_content_block py-12">
    <div class="container mx-auto px-4">

      <?php if ($content_type): ?>
        <div class="content_type-field"><?php echo esc_html($content_type); ?></div>
      <?php endif; ?>

      <?php if ($title): ?>
        <h2 class="text-3xl font-bold mb-6"><?php echo esc_html($title); ?></h2>
      <?php endif; ?>

      <?php if ($subtitle): ?>
        <h2 class="text-3xl font-bold mb-6"><?php echo esc_html($subtitle); ?></h2>
      <?php endif; ?>

      <?php if ($content): ?>
        <div class="content-content prose max-w-none">
          <?php echo wp_kses_post($content); ?>
        </div>
      <?php endif; ?>

      <?php if ($image): ?>
        <div class="image-wrapper">
          <?php if (function_exists('resplast_optimized_image')): ?>
            <?php echo resplast_optimized_image($image['ID'], 'large', [
              'class' => 'image-image',
              'alt' => $image['alt'] ?: '',
              'lazy' => true
            ]); ?>
          <?php else: ?>
            <img src="<?php echo esc_url($image['url']); ?>" 
                 alt="<?php echo esc_attr($image['alt']); ?>" 
                 class="image-image">
          <?php endif; ?>
        </div>
      <?php endif; ?>

      <?php if ($gallery_images): ?>
        <div class="gallery_images-field"><?php echo esc_html($gallery_images); ?></div>
      <?php endif; ?>

      <?php if ($background_color): ?>
        <div class="background_color-field"><?php echo esc_html($background_color); ?></div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
