<?php

/**
 * Related News Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - section_title (text)
 * - posts_to_show (number)
 * - show_category (true_false)
 * - show_date (true_false)
 */

$section_title = get_sub_field('section_title') ?: '';
$posts_to_show = get_sub_field('posts_to_show') ?: '';
$show_category = get_sub_field('show_category') ?: '';
$show_date = get_sub_field('show_date') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($section_title || $posts_to_show || $show_category)): ?>
  <section class="related_news_block py-12">
    <div class="container mx-auto px-4">

      <?php if ($section_title): ?>
        <h2 class="text-3xl font-bold mb-6"><?php echo esc_html($section_title); ?></h2>
      <?php endif; ?>

      <?php if ($posts_to_show): ?>
        <div class="posts_to_show-field"><?php echo esc_html($posts_to_show); ?></div>
      <?php endif; ?>

      <?php if ($show_category): ?>
        <div class="show_category-field"><?php echo esc_html($show_category); ?></div>
      <?php endif; ?>

      <?php if ($show_date): ?>
        <div class="show_date-field"><?php echo esc_html($show_date); ?></div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
