<?php

/**
 * Accordion Template (Vanilla JS)
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (text)
 * - description (wysiwyg)
 * - accordion_items (repeater)
 *   - heading (text)
 *   - content (wysiwyg)
 *   - accordion_image (image)
 * - cta (link)
 */

$title = get_sub_field('title') ?: '';
$description = get_sub_field('description') ?: '';
$accordion_items = get_sub_field('accordion_items') ?: '';
$cta = get_sub_field('cta') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $description || $accordion_items)): ?>
  <section class="accordion-section py-12">
    <div class="container mx-auto px-4">

      <?php if ($title): ?>
        <h2 class="text-3xl font-bold mb-6"><?php echo esc_html($title); ?></h2>
      <?php endif; ?>

      <?php if ($description): ?>
        <div class="description-content prose max-w-none">
          <?php echo wp_kses_post($description); ?>
        </div>
      <?php endif; ?>

      <?php if ($accordion_items): ?>
        <div class="accordion accordion_items-grid">
          <?php $i = 0; foreach ($accordion_items as $item): $i++; ?>
            <div class="accordion-item accordion_items-item">
              <button class="accordion-trigger" aria-expanded="false" aria-controls="accordion-content-about-<?php echo $i; ?>">
                <?php if ($item['heading']): ?>
                  <div class="heading"><?php echo esc_html($item['heading']); ?></div>
                <?php endif; ?>
              </button>
              <div id="accordion-content-about-<?php echo $i; ?>" class="accordion-panel" style="max-height: 0;">
                <?php if ($item['content']): ?>
                  <div class="content"><?php echo esc_html($item['content']); ?></div>
                <?php endif; ?>
                <?php if ($item['accordion_image']): ?>
                  <img src="<?php echo esc_url($item['accordion_image']['url']); ?>" alt="<?php echo esc_attr($item['accordion_image']['alt']); ?>">
                <?php endif; ?>
              </div>
            </div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>

      <?php if ($cta && $cta['url']): ?>
        <a href="<?php echo esc_url($cta['url']); ?>"
           class="btn btn-primary"
           <?php if ($cta['target']): ?>target="<?php echo esc_attr($cta['target']); ?>"<?php endif; ?>>
          <?php echo esc_html($cta['title'] ?: 'Read More'); ?>
        </a>
      <?php endif; ?>

    </div>
  </section>
<script>
  document.addEventListener('DOMContentLoaded', () => {
    document.querySelectorAll('.accordion-trigger').forEach(button => {
      button.addEventListener('click', () => {
        const panel = document.getElementById(button.getAttribute('aria-controls'));
        const isOpen = button.getAttribute('aria-expanded') === 'true';
        
        // Close all other panels in same accordion
        const accordion = button.closest('.accordion');
        if (accordion) {
          accordion.querySelectorAll('.accordion-panel').forEach(p => {
            p.style.maxHeight = '0';
          });
          accordion.querySelectorAll('.accordion-trigger').forEach(btn => {
            btn.setAttribute('aria-expanded', 'false');
          });
        }
        
        // Toggle current panel
        if (!isOpen && panel) {
          panel.style.maxHeight = panel.scrollHeight + 'px';
          button.setAttribute('aria-expanded', 'true');
        }
      });
    });
  });
</script>
<?php endif; ?>
