<?php

/**
 * Milestones Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (text)
 * - description (wysiwyg)
 * - milestones_items (repeater)
 *   - image (image)
 *   - year (text)
 *   - content (wysiwyg)
 */

$title = get_sub_field('title') ?: '';
$description = get_sub_field('description') ?: '';
$milestones_items = get_sub_field('milestones_items') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $description || $milestones_items)):
  $slide_count = is_array($milestones_items) ? count($milestones_items) : 0;
?>
  <section class="milestones_block fade-in relative" data-component="MilestonesSlider" data-slide-count="<?php echo esc_attr($slide_count); ?>">
    <div class="container-fluid">
      <div class="floating-item-left absolute left-[100px] top-0 -z-1 pointer-none w-[87px] lg:w-fit lg:block hidden" data-speed="1.25">
        <img src="<?= get_stylesheet_directory_uri(); ?>/assets/images/about/shape/shape-1.png" alt="">
      </div>
      <?php if ($title || $description): ?>
        <div class="section-heading text-center">
          <?php if ($title): ?>
            <h2 class="fade-text"><?php echo esc_html($title); ?></h2>
          <?php endif; ?>

          <?php if ($description): ?>
            <div class="description-content prose max-w-none anim-uni-in-up">
              <?php echo wp_kses_post($description); ?>
            </div>
          <?php endif; ?>
        </div>
      <?php endif; ?>


      <?php if ($milestones_items): ?>
        <?php $delay = 0; // initialize delay 
        ?>
        <div class="milestones-timeline ">

          <!-- Swiper container -->
          <div class="swiper milestones-swiper">
            <div class="swiper-wrapper overflow-visible fade-up-stagger-wrap">
              <?php foreach ($milestones_items as $index => $item):
                $delay += 0.2; // increment delay for stagger effect
              ?>
                <div class="swiper-slide milestone-slide fade-up-stagger" data-delay="<?php echo number_format($delay, 1); ?>">
                  <div class="milestone-card">

                    <!-- Image container -->
                    <?php if ($item['image']): ?>
                      <div class="image-wrapper overflow-hidden rounded-2xl bottom-right">
                        <img class="rounded-2xl" src="<?php echo esc_url($item['image']['url']); ?>" alt="<?php echo esc_attr($item['image']['alt']); ?>">
                      </div>
                    <?php endif; ?>

                    <div class="timeline-ruler">
                      <div class="top-line"></div>
                      <ul class="ruler-x">
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                      </ul>
                      <div class="line"></div>
                    </div>

                    <!-- Year -->
                    <?php if ($item['year']): ?>
                      <div class="milestone-year h3">
                        <?php echo esc_html($item['year']); ?>
                      </div>
                    <?php endif; ?>

                    <!-- Content -->
                    <?php if ($item['content']): ?>
                      <div class="milestone-content max-w-[197px] mx-auto">
                        <?php echo wp_kses_post($item['content']); ?>
                      </div>
                    <?php endif; ?>
                  </div>
                </div>
              <?php endforeach; ?>
            </div>

            <!-- Slider Navigation & Pagination -->
            <div class="swiper-navigation flex items-center justify-center mt-3 gap-4 relative z-20">
              <div class="swiper-btn-prev-pagination swiper-btn-prev">
                <svg xmlns="http://www.w3.org/2000/svg" width="9" height="7" viewBox="0 0 9 7" fill="none">
                  <path d="M7.92 3.18c.24 0 .44.2.44.45s-.2.44-.44.44H1.67l2.13 2.13a.44.44 0 01-.63.63L.59 4.26a.9.9 0 010-1.26l2.58-2.57a.44.44 0 01.63.63L1.67 3.18h6.25z" fill="#DA000E" />
                </svg>
              </div>

              <div class="swiper-pagination-custom text-primary text-xs font-medium !w-4 !h-4"></div>

              <div class="swiper-btn-next-pagination swiper-btn-next">
                <svg xmlns="http://www.w3.org/2000/svg" width="9" height="7" viewBox="0 0 9 7" fill="none">
                  <path d="M1.16 3.18a.44.44 0 000 .89h6.25L5.29 6.2a.44.44 0 10.63.63l2.58-2.58a.9.9 0 000-1.26L5.92.43a.44.44 0 10-.63.63l2.13 2.13H1.16z" fill="#DA000E" />
                </svg>
              </div>
            </div>
          </div>
        </div>
      <?php endif; ?>



    </div>
  </section>
<?php endif; ?>