<?php

/**
 * Accordion Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (text)
 * - description (wysiwyg)
 * - image (image)
 * - accordion_items (repeater)
 *   - heading (text)
 *   - content (textarea)
 *   - accordion_image (image)
 */

$title = get_sub_field('title') ?: '';
$description = get_sub_field('description') ?: '';
$image = get_sub_field('image') ?: '';
$accordion_items = get_sub_field('accordion_items') ?: '';
$cta         = get_sub_field('cta');

$cta_url    = ! empty($cta['url'])    ? esc_url($cta['url'])    : '';
$cta_title  = ! empty($cta['title'])  ? esc_html($cta['title']) : '';
$cta_target = ! empty($cta['target']) ? esc_attr($cta['target']) : '_self';
// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $description || $image)): ?>
    <section class="accordion_block fade-in relative" data-component="AccordionBlock">
        <div class="container-fluid">

            <div class="section-heading text-center !max-w-max">
                <?php if ($title): ?>
                    <h2 class="fade-text"><?php echo esc_html($title); ?></h2>
                <?php endif; ?>

                <?php if ($description): ?>
                    <div class="description-content prose max-w-none prose-p:text-grey-2 anim-uni-in-up">
                        <?php echo wp_kses_post($description); ?>
                    </div>
                <?php endif; ?>
            </div>

            <div class="flex flex-col gap-1 md:gap-3 items-center lg:items-stretch md:flex-row bg-sky-50 custom-rounded">
                <?php if ($image || ($accordion_items && !empty($accordion_items))): ?>
                    <div class="w-full sl:w-5/12 image-wrapper mx-auto bottom-right" data-accordion-image-container>
                        <?php
                        // Default image (main image or first accordion item image)
                        $default_image = $image;
                        if (!$default_image && $accordion_items) {
                            foreach ($accordion_items as $item) {
                                if (!empty($item['accordion_image'])) {
                                    $default_image = $item['accordion_image'];
                                    break;
                                }
                            }
                        }
                        ?>
                        <?php if ($default_image): ?>
                            <?php if (function_exists('resplast_optimized_image')): ?>
                                <?php echo resplast_optimized_image($default_image['ID'], 'large', [
                                    'class' => 'accordion-main-image custom-rounded size-full object-cover transition-opacity duration-300',
                                    'alt' => $default_image['alt'] ?: '',
                                    'lazy' => true,
                                    'data-image-id' => 'default',
                                    'style' => 'clip-path: inset(0 100% 0 0); opacity: 0;'
                                ]); ?>
                            <?php else: ?>
                                <img src="<?php echo esc_url($default_image['url']); ?>"
                                    alt="<?php echo esc_attr($default_image['alt']); ?>"
                                    class="accordion-main-image custom-rounded size-full object-cover transition-opacity duration-300"
                                    style="clip-path: inset(0 100% 0 0); opacity: 0;"
                                    data-image-id="default">
                            <?php endif; ?>
                        <?php endif; ?>

                        <?php if ($accordion_items): ?>
                            <?php $i = 0;
                            foreach ($accordion_items as $item): $i++; ?>
                                <?php if (!empty($item['accordion_image'])): ?>
                                    <?php if (function_exists('resplast_optimized_image')): ?>
                                        <?php echo resplast_optimized_image($item['accordion_image']['ID'], 'large', [
                                            'class' => 'accordion-item-image custom-rounded size-full object-cover transition-opacity duration-300 absolute inset-0 opacity-0',
                                            'alt' => $item['accordion_image']['alt'] ?: '',
                                            'lazy' => true,
                                            'data-image-id' => 'accordion-' . $i,
                                            'style' => 'clip-path: inset(0 100% 0 0);'
                                        ]); ?>
                                    <?php else: ?>
                                        <img src="<?php echo esc_url($item['accordion_image']['url']); ?>"
                                            alt="<?php echo esc_attr($item['accordion_image']['alt']); ?>"
                                            class="accordion-item-image custom-rounded size-full object-cover transition-opacity duration-300 absolute inset-0 opacity-0"
                                            style="clip-path: inset(0 100% 0 0);"
                                            data-image-id="accordion-<?php echo $i; ?>">
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>

                <?php if ($accordion_items): ?>
                    <div class="w-full sl:w-7/12 accordion_items-grid  p-4 sl:p-8 relative">
                        <?php $i = 0;
                        foreach ($accordion_items as $item): $i++;
                            $is_open = $i === 1; ?>
                            <div class="accordion_items-item border-b border-grey-7/20 last:border-b-0">
                                <div class="accordion-trigger w-full flex items-center justify-between gap-4 py-3 md:py-6 cursor-pointer"
                                    role="button"
                                    tabindex="0"
                                    aria-expanded="<?php echo $is_open ? 'true' : 'false'; ?>"
                                    aria-controls="acc-content-<?php echo $i; ?>"
                                    data-accordion-index="<?php echo $i; ?>"
                                    <?php if (!empty($item['accordion_image'])): ?>
                                    data-has-image="true"
                                    <?php endif; ?>>
                                    <div class="text-left">
                                        <?php if ($item['heading']): ?>
                                            <div class="heading h3 text-grey-1 font-semibold tracking-[-0.48px]"><?php echo esc_html($item['heading']); ?></div>
                                        <?php endif; ?>
                                    </div>
                                    <span class="icon-wrap shrink-0 inline-flex items-center justify-center rounded-full bg-primary text-white size-5 lg:size-8">
                                        <svg class="plus w-4 h-4 <?php echo $is_open ? 'hidden' : 'block'; ?>" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M12 5v14M5 12h14" />
                                        </svg>
                                        <svg class="minus w-4 h-4 <?php echo $is_open ? 'block' : 'hidden'; ?>" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M5 12h14" />
                                        </svg>
                                    </span>
                                </div>
                                <div id="acc-content-<?php echo $i; ?>" class="accordion-panel <?php echo $is_open ? 'block' : 'hidden'; ?> pb-5 lg:pb-6 pr-12">
                                    <?php if ($item['content']): ?>
                                        <div class="content body-1 text-grey-2 porse-p:font-normal font-normal">
                                            <?php echo wp_kses_post($item['content']); ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
            <?php if ($cta_url && $cta_title) : ?>
                <div class="text-center mt-4">
                    <a href="<?php echo $cta_url; ?>" target="<?php echo $cta_target; ?>" class="btn">
                        <?php echo $cta_title; ?>
                    </a>
                </div>
            <?php endif; ?>

        </div>
        <!-- Decorative Shape (Mobile) -->
        <div id="scroll-frame" class="lg:block hidden absolute left-[-81px] top-0 -z-1 pointer-none w-[170px] " data-scroll-frame>
            <img class="" src="<?= get_stylesheet_directory_uri(); ?>/assets/images/research/shape-1.png" alt="">
        </div>
        <div class="lg:block hidden absolute right-[0] top-0 -z-1 pointer-none w-[170px]">
            <img class="" src="<?= get_stylesheet_directory_uri(); ?>/assets/images/research/shape-2.png" alt="">
        </div>
    </section>
<?php endif; ?>