<?php

/**
 * Accordion Template (Vanilla JS)
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (text)
 * - description (wysiwyg)
 * - accordion_items (repeater)
 *   - heading (text)
 *   - content (wysiwyg)
 *   - accordion_image (image)
 * - cta (link)
 */

$title = get_sub_field('title') ?: '';
$description = get_sub_field('description') ?: '';
$accordion_items = get_sub_field('accordion_items') ?: '';
$cta = get_sub_field('cta') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $description || $accordion_items)): ?>
<section class="accordion-section" data-component="AccordionBlock">
    <div class="container mx-auto px-4 max-w-6xl">

      <!-- Section Heading -->
      <div class="section-heading text-center mb-10 lg:mb-14">
        <?php if ($title): ?>
          <h2 class="text-3xl md:text-4xl lg:text-5xl font-bold text-gray-900 mb-4">
            <?php echo esc_html($title); ?>
          </h2>
        <?php endif; ?>

        <?php if ($description): ?>
          <div class="prose max-w-prose mx-auto text-gray-600">
            <?php echo wp_kses_post($description); ?>
          </div>
        <?php endif; ?>
      </div>

      <!-- Accordion -->
      <?php if ($accordion_items): ?>
        <div class="accordion rounded-xl overflow-hidden shadow-md bg-white">
          <?php $i = 0; foreach ($accordion_items as $item): $i++; ?>
            <div class="accordion-item border-b border-gray-200 last:border-b-0">
              <!-- Accordion Header -->
              <button 
                class="accordion-trigger w-full flex items-center justify-between text-left py-5 px-6 hover:bg-gray-50 transition-colors duration-150"
                aria-expanded="false"
                aria-controls="accordion-content-<?php echo $i; ?>">
                
                <?php if ($item['heading']): ?>
                  <h3 class="text-lg font-semibold text-gray-900">
                    <?php echo esc_html($item['heading']); ?>
                  </h3>
                <?php endif; ?>
                
                <span class="ml-4 flex-shrink-0">
                  <svg class="h-6 w-6 text-red-600 transition-transform duration-200 accordion-icon"
                       xmlns="http://www.w3.org/2000/svg" 
                       viewBox="0 0 24 24" 
                       fill="none" 
                       stroke="currentColor" 
                       stroke-width="2" 
                       stroke-linecap="round" 
                       stroke-linejoin="round">
                    <polyline points="6 9 12 15 18 9"></polyline>
                  </svg>
                </span>
              </button>
              
              <!-- Accordion Content -->
              <div 
                id="accordion-content-<?php echo $i; ?>" 
                class="accordion-panel overflow-hidden transition-all max-h-0 duration-300 ease-in-out"
                style="max-height: 0;">
                
                <div class="p-6 pt-0">
                  <!-- Flex container for content and image -->
                  <div class="flex flex-col md:flex-row gap-6">
                    <!-- Content Column -->
                    <div class="md:w-7/12">
                      <?php if ($item['content']): ?>
                        <div class="prose max-w-none text-gray-600">
                          <?php echo wp_kses_post($item['content']); ?>
                        </div>
                      <?php endif; ?>
                    </div>
                    
                    <!-- Image Column (if exists) -->
                    <?php if (!empty($item['accordion_image'])): ?>
                      <div class="md:w-5/12">
                        <?php if (function_exists('resplast_optimized_image')): ?>
                          <?php echo resplast_optimized_image($item['accordion_image']['ID'], 'medium_large', [
                            'class' => 'w-full h-auto rounded-lg shadow-sm',
                            'alt' => $item['accordion_image']['alt'] ?: '',
                            'lazy' => true,
                          ]); ?>
                        <?php else: ?>
                          <img 
                            src="<?php echo esc_url($item['accordion_image']['url']); ?>" 
                            alt="<?php echo esc_attr($item['accordion_image']['alt']); ?>"
                            class="w-full h-auto rounded-lg shadow-sm">
                        <?php endif; ?>
                      </div>
                    <?php endif; ?>
                  </div>
                </div>
              </div>
            </div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>
      
      <!-- CTA Button -->
      <?php if ($cta && $cta['url']): ?>
        <div class="text-center mt-10">
          <a href="<?php echo esc_url($cta['url']); ?>"
             class="inline-block bg-red-600 hover:bg-red-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-200"
             <?php if ($cta['target']): ?>target="<?php echo esc_attr($cta['target']); ?>"<?php endif; ?>>
            <?php echo esc_html($cta['title'] ?: 'Read More'); ?>
          </a>
        </div>
      <?php endif; ?>

    </div>
  </section>
<script>
  document.addEventListener('DOMContentLoaded', () => {
    document.querySelectorAll('.accordion-trigger').forEach(button => {
      button.addEventListener('click', () => {
        const panel = document.getElementById(button.getAttribute('aria-controls'));
        const isOpen = button.getAttribute('aria-expanded') === 'true';
        
        // Close all other panels
        document.querySelectorAll('.accordion-panel').forEach(p => {
          p.style.maxHeight = '0';
        });
        document.querySelectorAll('.accordion-trigger').forEach(btn => {
          btn.setAttribute('aria-expanded', 'false');
          btn.querySelector('.accordion-icon')?.classList.remove('rotate-180');
        });
        
        // Toggle current panel
        if (!isOpen && panel) {
          panel.style.maxHeight = panel.scrollHeight + 'px';
          button.setAttribute('aria-expanded', 'true');
          button.querySelector('.accordion-icon')?.classList.add('rotate-180');
        }
      });
    });
  });
</script>
<?php endif; ?>
