<?php

/**
 * ESG CSR Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (text)
 * - description (wysiwyg)
 * - esg_items (repeater)
 *   - layout_type (select: 'quote' or 'certification')
 *   - quote_content (wysiwyg)
 *   - quote_name (text)
 *   - quote_designation (text)
 *   - badge_image (image)
 *   - badge_title (text)
 *   - badge_description (wysiwyg)
 *   - badge_link (link)
 */

$title = get_sub_field('title') ?: '';
$description = get_sub_field('description') ?: '';
$esg_items = get_sub_field('esg_items') ?: [];

// DEBUG: Check if esg_items exists
// error_log('ESG Items count: ' . count($esg_items));

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $description || !empty($esg_items))):
  $has_items = !empty($esg_items) && count($esg_items) > 0;
?>
  <!-- DEBUG: Has Items: <?php echo $has_items ? 'YES (' . count($esg_items) . ')' : 'NO'; ?> -->
  <section class="esg_csr_block fade-in" <?php echo $has_items ? 'data-component="ESGSlider" data-load="eager"' : ''; ?>>
    <div class="container-fluid">

      <div class="section-heading text-center">
        <?php if ($title): ?>
          <h2 class="fade-text"><?php echo esc_html($title); ?></h2>
        <?php endif; ?>

        <?php if ($description): ?>
          <div class="description-content prose max-w-none anim-uni-in-up">
            <?php echo wp_kses_post($description); ?>
          </div>
        <?php endif; ?>
      </div>

      <!-- DEBUG: ESG Items Count: <?php echo count($esg_items); ?> -->
      <?php if (!empty($esg_items)): ?>
        <div class="esg-slider-container">
          <div class="swiper esg-slider">
            <div class="swiper-wrapper">
              <?php foreach ($esg_items as $item):
                $layout_type = $item['layout_type'] ?? 'quote';
              ?>
                <div class="swiper-slide">
                  <div class="bg-[#EEF7E7] rounded-[32px] relative max-w-max sm:max-w-[500px] md:max-w-[1026px] mx-auto bottom-right">

                    <?php if ($layout_type === 'quote'): ?>
                      <!-- Quote Layout -->
                      <div class="relative quote-card flex flex-col md:flex-row items-center justify-between gap-8 p-6 md:p-14">
                        <!-- Quote Section -->
                        <div class="order-2 md:order-1 w-full md:w-8/12 flex gap-3 md:gap-7 relative ">
                          <!-- Large Red Quote Mark -->
                          <div class="select-none" aria-hidden="true">
                            <svg class="max-sm:w-[42px] w-[75px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 75 63" fill="none">
                              <path d="M42.3828 62.2881V39.9997C42.3828 30.0495 45.0521 21.3597 50.3906 13.9302C55.7292 6.3681 63.9323 1.72469 75 0V14.5273C68.6198 15.3233 64.388 17.446 62.3047 20.8954C60.2214 24.3448 59.1797 28.9219 59.1797 34.6266L47.6562 32.2386H74.6094V62.2881H42.3828ZM0 62.2881V39.9997C0 30.0495 2.66927 21.3597 8.00781 13.9302C13.3464 6.3681 21.5495 1.72469 32.6172 0V14.5273C26.237 15.3233 22.0052 17.446 19.9219 20.8954C17.8385 24.3448 16.7969 28.9219 16.7969 34.6266L5.27344 32.2386H32.2266V62.2881H0Z" fill="#DA000E" />
                            </svg>
                          </div>

                          <div class="flex flex-col gap-5 md:gap-10 max-w-[416px]">
                            <?php if (!empty($item['quote_content'])): ?>
                              <div class="quote_content-content prose max-w-none text-[#111] prose-p:text-sm md:prose-p:text-2xl md:prose-p:leading-[36px] prose-p:font-normal">
                                <?php echo wp_kses_post($item['quote_content']); ?>
                              </div>
                            <?php endif; ?>

                            <!-- Author Information -->
                            <div>
                              <div class="author-info">
                                <?php if (!empty($item['quote_name'])): ?>
                                  <div class="quote_name-text body-1 text-grey-7 font-semibold leading-[26px] tracking-[0.36px] md:mb-1"><?php echo esc_html($item['quote_name']); ?></div>
                                <?php endif; ?>

                                <?php if (!empty($item['quote_designation'])): ?>
                                  <div class="quote_designation-text body-1 text-grey-7 font-normal leading-relaxed tracking-[0.36px]"><?php echo esc_html($item['quote_designation']); ?></div>
                                <?php endif; ?>
                              </div>

                            </div>
                          </div>
                        </div>

                        <!-- Badge Image -->
                        <?php if (!empty($item['badge_image'])): ?>
                          <div class="order-1 md:order-2 w-full md:w-4/12 flex flex-col gap-6 justify-center items-center">
                            <div class="size-[200px]">
                              <?php if (function_exists('resplast_optimized_image')): ?>
                                <?php echo resplast_optimized_image($item['badge_image']['ID'], 'large', [
                                  'class' => 'w-full h-full object-contain',
                                  'alt' => $item['badge_image']['alt'] ?: '',
                                  'lazy' => true
                                ]); ?>
                              <?php else: ?>
                                <img src="<?php echo esc_url($item['badge_image']['url']); ?>"
                                  alt="<?php echo esc_attr($item['badge_image']['alt']); ?>"
                                  class="w-full h-full object-contain">
                              <?php endif; ?>
                            </div>

                            <!-- Quote Link (Download) -->
                            <?php if (!empty($item['quote_link'])): ?>
                              <a href="<?php echo esc_url($item['quote_link']['url']); ?>"
                                class="inline-flex items-center gap-2 text-primary font-semibold text-sm"
                                download
                                <?php echo !empty($item['quote_link']['target']) ? 'target="' . esc_attr($item['quote_link']['target']) . '"' : ''; ?>>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
                                  <path d="M14 10V12.6667C14 13.0203 13.8595 13.3594 13.6095 13.6095C13.3594 13.8595 13.0203 14 12.6667 14H3.33333C2.97971 14 2.64057 13.8595 2.39052 13.6095C2.14048 13.3594 2 13.0203 2 12.6667V10" stroke="#DA000E" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" />
                                  <path d="M4.66602 6.66687L7.99935 10.0002L11.3327 6.66687" stroke="#DA000E" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" />
                                  <path d="M8 10V2" stroke="#DA000E" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                                <?php echo esc_html($item['quote_link']['title'] ?: 'RPL GRI Report'); ?>
                              </a>
                            <?php endif; ?>
                          </div>
                        <?php endif; ?>
                      </div>

                    <?php else: ?>
                      <!-- Certification Badge Layout -->
                      <div class="relative certification-card flex flex-col md:flex-row items-start justify-between gap-8 p-6 md:p-12">
                        <!-- Text Content -->
                        <div class="order-2 md:order-1 w-full md:w-7/12 flex flex-col gap-2">
                          <?php if (!empty($item['badge_title'])): ?>
                            <div class="md:text-2xl prose-strong:block text-grey-7"><?php echo ($item['badge_title']); ?></div>
                          <?php endif; ?>

                          <?php if (!empty($item['badge_description'])): ?>
                            <div class="md:prose-p:text-[18px] prose-p:text-sm prose-p:text-[#111] prose-p:leading-[26px]">
                              <?php echo wp_kses_post($item['badge_description']); ?>
                            </div>
                          <?php endif; ?>


                        </div>

                        <!-- Badge Image -->
                        <?php if (!empty($item['badge_image'])): ?>
                          <div class="order-1 md:order-2 w-full md:w-5/12 flex justify-center items-center flex-col gap-4 md:gap-8">
                            <div class="max-w-[280px]">
                              <?php if (function_exists('resplast_optimized_image')): ?>
                                <?php echo resplast_optimized_image($item['badge_image']['ID'], 'large', [
                                  'class' => 'w-full h-auto object-contain',
                                  'alt' => $item['badge_image']['alt'] ?: '',
                                  'lazy' => true
                                ]); ?>
                              <?php else: ?>
                                <img src="<?php echo esc_url($item['badge_image']['url']); ?>"
                                  alt="<?php echo esc_attr($item['badge_image']['alt']); ?>"
                                  class="w-full h-auto object-contain">
                              <?php endif; ?>
                            </div>
                            <?php if (!empty($item['badge_link'])): ?>
                              <a href="<?php echo esc_url($item['badge_link']['url']); ?>"
                                class="inline-flex items-center gap-2 text-primary text-sm font-semibold "
                                <?php echo !empty($item['badge_link']['target']) ? 'target="' . esc_attr($item['badge_link']['target']) . '"' : ''; ?>>
                                <div class="bg-primary size-4 rounded-[3px] flex items-center justify-center">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="8" height="8" viewBox="0 0 8 8" fill="none">
                                    <path d="M0 0.885041C0 0.628502 0.0900927 0.416862 0.27027 0.25012C0.450448 0.0833708 0.684687 0 0.972973 0C1.25612 0 1.4852 0.0820856 1.66023 0.246272C1.84041 0.415584 1.9305 0.636198 1.9305 0.908129C1.9305 1.1544 1.84299 1.35962 1.66795 1.52381C1.48778 1.69312 1.25097 1.77778 0.957529 1.77778H0.949807C0.666664 1.77778 0.437583 1.69312 0.262548 1.52381C0.0875135 1.3545 0 1.14157 0 0.885041ZM0.100386 7.61904V2.47811H1.81467V7.61904H0.100386ZM2.76448 7.61904H4.47876V4.74843C4.47876 4.56886 4.49936 4.43033 4.54054 4.33285C4.61261 4.15841 4.72201 4.0109 4.86873 3.89033C5.01544 3.76976 5.19948 3.70947 5.42085 3.70947C5.99743 3.70947 6.28571 4.09684 6.28571 4.87157V7.61904H8V4.67148C8 3.91213 7.81982 3.33622 7.45946 2.94372C7.0991 2.55123 6.62291 2.35498 6.03089 2.35498C5.3668 2.35498 4.84942 2.63973 4.47876 3.20923V3.22463H4.47104L4.47876 3.20923V2.47811H2.76448C2.77477 2.64229 2.77992 3.15279 2.77992 4.00962C2.77992 4.86644 2.77477 6.06958 2.76448 7.61904Z" fill="white" />
                                  </svg>
                                </div>
                                <?php echo esc_html($item['badge_link']['title'] ?: 'Read More'); ?>

                              </a>
                            <?php endif; ?>
                          </div>
                        <?php endif; ?>
                      </div>
                    <?php endif; ?>

                  </div>
                </div>
              <?php endforeach; ?>
            </div>
          </div>

          <!-- Navigation Controls (Latest News style) -->
          <?php if (count($esg_items) > 1): ?>
            <div class="mt-3 flex justify-center items-center gap-3 esg-navigation">
              <div class="swiper-btn-prev-pagination swiper-btn-prev">
                <svg xmlns="http://www.w3.org/2000/svg" width="9" height="7" viewBox="0 0 9 7" fill="none">
                  <path d="M7.92214 3.18291C8.16739 3.18291 8.36621 3.38173 8.36621 3.62699C8.36621 3.87224 8.16739 4.07106 7.92214 4.07106L1.66704 4.07106L3.79543 6.19944C3.96885 6.37286 3.96885 6.65403 3.79543 6.82745C3.62201 7.00087 3.34084 7.00087 3.16742 6.82745L0.594961 4.255C0.24812 3.90816 0.24812 3.34581 0.594961 2.99897L3.16742 0.426516C3.34084 0.253095 3.62201 0.253096 3.79543 0.426516C3.96885 0.599937 3.96885 0.881107 3.79543 1.05453L1.66705 3.18291L7.92214 3.18291Z" fill="#DA000E" />
                </svg>
              </div>

              <div class="swiper-pagination-custom text-primary text-xs font-medium !w-4 !h-4"></div>

              <div class="swiper-btn-next-pagination swiper-btn-next">
                <svg xmlns="http://www.w3.org/2000/svg" width="9" height="7" viewBox="0 0 9 7" fill="none">
                  <path d="M1.15891 3.18291C0.913661 3.18291 0.714844 3.38173 0.714844 3.62699C0.714844 3.87224 0.913661 4.07106 1.15892 4.07106L7.41401 4.07106L5.28562 6.19944C5.1122 6.37286 5.1122 6.65403 5.28562 6.82745C5.45904 7.00087 5.74021 7.00087 5.91364 6.82745L8.48609 4.255C8.83293 3.90816 8.83294 3.34581 8.48609 2.99897L5.91363 0.426516C5.74021 0.253095 5.45904 0.253096 5.28562 0.426516C5.1122 0.599937 5.1122 0.881107 5.28562 1.05453L7.41401 3.18291L1.15891 3.18291Z" fill="#DA000E" />
                </svg>
              </div>
            </div>
          <?php endif; ?>
        </div>
      <?php endif; ?>

    </div>
  </section>
<?php endif; ?>