<?php

/**
 * Leadership Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (text)
 * - description (wysiwyg)
 * - leaders_image (image)
 * - quote_message (wysiwyg)
 * - leader_title (text)
 * - leadere_designation (text)
 */

$title = get_sub_field('title') ?: '';
$description = get_sub_field('description') ?: '';
$leaders_image = get_sub_field('leaders_image') ?: '';
$quote_message = get_sub_field('quote_message') ?: '';
$leader_title = get_sub_field('leader_title') ?: '';
$leadere_designation = get_sub_field('leadere_designation') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $description || $leaders_image)): ?>
  <section class="leadership_block fade-in" data-component="LeadershipBlock">
    <div class="container-fluid">

      <div class="section-heading text-center lg:pb-10">
        <?php if ($title): ?>
          <h2 class="fade-text"><?php echo esc_html($title); ?></h2>
        <?php endif; ?>

        <?php if ($description): ?>
          <div class="description-content prose max-w-none anim-uni-in-up">
            <?php echo wp_kses_post($description); ?>
          </div>
        <?php endif; ?>
      </div>

      <div class="flex lg:flex-row flex-col  gap-8 lg:gap-15 justify-center">
        <?php if ($leaders_image): ?>
          <div class="leaders_image-wrapper  relative flex justify-center items-end lg:order-1 order-2">
            <div class="">

              <img class="size-full object-cover" src="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/team/bg-blue.png" alt="">
            </div>
            <div class="absolute bottom-0 left-0 mx-auto right-0 w-full h-full flex items-end justify-center  custom-rounded max-md:w-[212px]">
              <?php if (function_exists('resplast_optimized_image')): ?>
                <?php echo resplast_optimized_image($leaders_image['ID'], 'large', [
                  'class' => 'leaders_image-image',
                  'alt' => $leaders_image['alt'] ?: '',
                  'lazy' => true
                ]); ?>
              <?php else: ?>
                <img src="<?php echo esc_url($leaders_image['url']); ?>"
                  alt="<?php echo esc_attr($leaders_image['alt']); ?>"
                  class="leaders_image-image">
              <?php endif; ?>
            </div>
          </div>
        <?php endif; ?>

        <div class="quote-section  flex items-start gap-4 lg:gap-10 justify-between max-w-[500px] max-lg:mx-auto max-lg:pb-10 lg:order-2 order-1">
          <img class="max-lg:size-[29px]" src="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/icons/quote.svg" alt="">
          <div class="flex flex-col gap-4 lg:gap-10">
            <?php if ($quote_message): ?>
              <div class="quote_message-content quote_content-content prose max-w-none text-[#111] prose-p:text-sm md:prose-p:text-2xl md:prose-p:leading-[36px] prose-p:font-normal">

                <?php echo wp_kses_post($quote_message); ?>
              </div>
            <?php endif; ?>

            <div class="">
              <?php if ($leader_title): ?>
                <div class="quote_name-text body-1 text-grey-7 font-semibold leading-[26px] tracking-[0.36px] md:mb-1"><?php echo esc_html($leader_title); ?></div>
              <?php endif; ?>

              <?php if ($leadere_designation): ?>
                <div class="quote_designation-text body-1 text-grey-7 font-normal leading-[26px] tracking-[0.36px]"><?php echo esc_html($leadere_designation); ?></div>
              <?php endif; ?>
            </div>
          </div>


        </div>
      </div>




    </div>
  </section>
<?php endif; ?>