<?php

/**
 * Privacy Accordion Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - acc (repeater)
 *   - title (text)
 *   - content (wysiwyg)
 */

$acc = get_sub_field('acc') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($acc)): ?>
  <section class="privacy_accordion_block" data-component="PrivacyAccordion">
    <div class="container-fluid ">
      <div class=" bg-sky-50 px-4 md:px-12 md:pb-12 pb-14 pt-3 rounded-3xl bottom-right">
        <?php foreach ($acc as $index => $item): ?>
          <div class="accordion-item  overflow-hidden border-b border-grey-7/20 last:border-0">
            <button class="accordion-toggle w-full px-0 py-3 md:py-6 flex items-center justify-between " data-accordion="accordion-<?php echo $index; ?>">
              <span class="text-base md:text-2xl font-semibold text-grey-1 tracking-[-0.48px]"><?php echo esc_html($item['title']); ?></span>
              <span class="accordion-icon bg-primary rounded-full size-5 md:size-8 flex items-center justify-center flex-shrink-0 p-1">
                <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M12 4v16m8-8H4" class="plus-icon"></path>
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M4 12h16" class="minus-icon hidden"></path>
                </svg>
              </span>
            </button>
            <div id="accordion-<?php echo $index; ?>" class="accordion-content  ">
              <div class="md:pb-6 pb-4 list-square">
                <?php echo wp_kses_post($item['content']); ?>
              </div>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
    </div>
  </section>
<?php endif; ?>