<?php

/**
 * Sustainability Impact Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (text)
 * - description (wysiwyg)
 * - tabs (repeater)
 *   - tab_label (text)
 *   - tab_slug (text)
 *   - hero_image (image)
 *   - stats (repeater)
 *     - stat_number (text)
 *     - stat_label (text)
 *     - stat_description (textarea)
 * - default_active_tab (number)
 */

$title = get_sub_field('title') ?: '';
$description = get_sub_field('description') ?: '';
$tabs = get_sub_field('tabs') ?: [];
$default_active_tab = get_sub_field('default_active_tab') ?: 0;

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block): ?>
  <section class="sustainability_impact_block fade-in relative section-triger" data-component="SustainabilityImpactBlock">
    <div class="container-fluid ">

      <!-- Header Section -->
      <div class="section-heading text-center">
        <?php if ($title): ?>
          <h2 class="fade-text"><?php echo esc_html($title); ?></h2>
        <?php endif; ?>

        <?php if ($description): ?>
          <div class="description-content anim-uni-in-up">
            <?php echo wp_kses_post($description); ?>
          </div>
        <?php endif; ?>


      </div>

      <?php if (!empty($tabs) && count($tabs) > 1): ?>
        <!-- Dynamic Tab Buttons -->
        <div class="impact-tabs mb-8 ">
          <div class="flex justify-center">
            <div class="relative inline-flex border-primary border rounded-full ">
              <!-- Active state background that slides -->
              <div class="absolute top-1 bottom-1 bg-primary rounded-full transition-all duration-300 ease-out"
                style="width: calc(50% - 4px); left: <?php echo $default_active_tab === 0 ? '4px' : '50%'; ?>;"></div>

              <?php foreach ($tabs as $index => $tab): ?>
                <?php
                $tab_label = $tab['tab_label'] ?? "Tab " . ($index + 1);
                $tab_slug = (!empty($tab['tab_slug'])) ? $tab['tab_slug'] : sanitize_title($tab_label);
                $is_active = ($index === $default_active_tab);
                ?>
                <div
                  class="impact-tab-btn relative z-10 text-sm font-bold px-6 py-3 rounded-full transition-all duration-300 cursor-pointer flex-1 text-center <?php echo $is_active ? 'text-white' : 'text-primary'; ?>"
                  data-tab="<?php echo esc_attr($tab_slug); ?>"
                  data-index="<?php echo $index; ?>">
                  <?php echo esc_html($tab_label); ?>
                </div>
              <?php endforeach; ?>
            </div>
          </div>
        </div>
      <?php endif; ?>

      <!-- Dynamic Tab Contents -->
      <?php if (!empty($tabs)): ?>
        <div class="impact-tab-contents ">
          <?php foreach ($tabs as $index => $tab): ?>
            <?php
            $tab_slug = (!empty($tab['tab_slug'])) ? $tab['tab_slug'] : sanitize_title($tab['tab_label'] ?? 'tab');
            $hero_image = $tab['hero_image'] ?? null;
            $stats = $tab['stats'] ?? [];
            $is_active = ($index === $default_active_tab);
            ?>

            <div
              class="impact-tab-content <?php echo $is_active ? 'active opacity-100' : 'hidden opacity-0'; ?>"
              data-tab="<?php echo esc_attr($tab_slug); ?>">
              <!-- Hero Image Section -->
              <?php if ($hero_image): ?>
                <div class="hero-section mb-2 md:mb-12">
                  <div class="">
                    <div class="custom-rounded overflow-hidden bottom-right relative">
                      <?php if (function_exists('resplast_optimized_image')): ?>
                        <?php echo resplast_optimized_image($hero_image['ID'], 'full', [
                          'class' => 'w-full h-auto object-cover myimg max-sm:aspect-[2]',
                          'alt' => ($hero_image['alt'] ?? '') ?: (($tab['tab_label'] ?? '') . ' Image'),
                          'lazy' => true
                        ]); ?>
                      <?php else: ?>
                        <img
                          src="<?php echo esc_url($hero_image['url']); ?>"
                          alt="<?php echo esc_attr(($hero_image['alt'] ?? '') ?: (($tab['tab_label'] ?? '') . ' Image')); ?>"
                          class="w-full h-auto object-cover myimg"
                          loading="lazy" />
                      <?php endif; ?>
                      <div class="uncover">
                        <div class="uncover_slice"></div>
                        <div class="uncover_slice"></div>
                        <div class="uncover_slice"></div>
                      </div>
                    </div>
                  </div>
                </div>
              <?php endif; ?>

              <!-- Stats Section -->
              <?php if (!empty($stats)): ?>
                <div class="stats-section" data-animate-on-scroll="true">
                  <div class="grid  grid-cols-2 lg:grid-cols-4 gap-4 md:gap-8  mx-auto">
                    <?php foreach ($stats as $stat_index => $stat): ?>
                      <?php
                      $stat_number = $stat['stat_number'] ?? '';
                      $stat_label = $stat['stat_label'] ?? '';
                      $stat_description = $stat['stat_description'] ?? '';
                      ?>

                      <div class="stat-item  group text-center">
                        <?php if ($stat_number): ?>
                          <div class="stat-number text-[31px] leading-[35px] max-md:tracking-[-0.76px]  md:text-[60px] md:leading-[54px] focus-within: font-medium text-primary mb-2">
                            <?php
                            // Check if the stat contains meaningful numbers for animation
                            $numeric_value = preg_replace('/[^0-9.]/', '', $stat_number);
                            $has_numbers = !empty($numeric_value) && $numeric_value !== '0';
                            ?>
                            <?php if ($has_numbers): ?>
                              <span class="counter-number" data-target="<?php echo esc_attr($numeric_value); ?>">
                                <?php echo esc_html($stat_number); ?>
                              </span>
                            <?php else: ?>
                              <span class="stat-text">
                                <?php echo esc_html($stat_number); ?>
                              </span>
                            <?php endif; ?>
                          </div>
                        <?php endif; ?>

                        <?php if ($stat_label): ?>
                          <div class="stat-label text-sm text-grey-2 font-medium leading-[17px] tracking-[0.14px]">
                            <?php echo esc_html($stat_label); ?>
                          </div>
                        <?php endif; ?>

                        <?php if ($stat_description): ?>
                          <p class="stat-description text-sm text-grey-3 leading-relaxed ">
                            <?php echo esc_html($stat_description); ?>
                          </p>
                        <?php endif; ?>
                      </div>
                    <?php endforeach; ?>
                  </div>
                </div>
              <?php endif; ?>
            </div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>

    </div>
  </section>

  <?php
  // CSS is imported in main stylesheet (assets/css/style.css)
  // JavaScript is loaded dynamically via data-component="SustainabilityImpactBlock"
  ?>
<?php endif; ?>