<?php

/**
 * test cc Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - title (text)
 */

$title = get_sub_field('title') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title)): ?>
  <section class="test_cc py-12">
    <div class="container mx-auto px-4">

      <?php if ($title): ?>
        <h2 class="text-3xl font-bold mb-6"><?php echo esc_html($title); ?></h2>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
