<?php

/**
 * Certificate Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (text)
 * - description (wysiwyg)
 * - certificate_items (repeater)
 *   - certificate_image (image)
 *   - certificate_no (text)
 *   - certificate_date (text)
 *   - certificate_link (link)
 *   - certificate_popup_image (image)
 */

$title = get_sub_field('title') ?: '';
$description = get_sub_field('description') ?: '';
$certificate_items = get_sub_field('certificate_items') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $description || $certificate_items)):
  $certificate_count = is_array($certificate_items) ? count($certificate_items) : 0;
  $use_slider = $certificate_count >= 1; // Always use slider for certificates
?>
  <section class="certificate_block fade-in relative" data-component="CertificateModal">
    <div class="container-fluid">
      <div class="floating-item-left absolute right-[100px] top-0 -z-1 pointer-none w-[87px] lg:w-fit lg:block hidden" data-speed="1.25">
        <img src="<?= get_stylesheet_directory_uri(); ?>/assets/images/about/shape/shape-2.png" alt="">
      </div>
      <div class="section-heading text-center">
        <?php if ($title): ?>
          <h2 class="fade-text"><?php echo esc_html($title); ?></h2>
        <?php endif; ?>

        <?php if ($description): ?>
          <div class="description-content prose max-w-none anim-uni-in-up">
            <?php echo wp_kses_post($description); ?>
          </div>
        <?php endif; ?>
      </div>

      <?php if ($certificate_items): ?>
        <?php
        $delay = 0; // ✅ initialize before loop
        ?>
        <!-- Certificate Slider Container -->
        <div class="certificate-slider-container"
          data-component="CertificateSlider"
          data-slider-enabled="<?php echo $use_slider ? 'true' : 'false'; ?>"
          data-certificate-count="<?php echo esc_attr($certificate_count); ?>">

          <!-- Swiper Slider -->
          <div class="certificate-slider swiper fade-up-stagger-wrap">
            <div class="swiper-wrapper">
              <?php foreach ($certificate_items as $index => $item):
                $delay += 0.2; // ✅ increment delay
              ?>
                <div class="swiper-slide">
                  <div class="certificate_items-item bottom-right fade-up-stagger" data-delay="<?php echo number_format($delay, 1); ?>">
                    <!-- Certificate Display Image -->
                    <?php if ($item['certificate_image']): ?>
                      <div class="certificate-image-container bg-[#EFF9FE] flex items-center justify-center p-4 rounded-t-2xl">
                        <img src="<?php echo esc_url($item['certificate_image']['url']); ?>"
                          alt="<?php echo esc_attr($item['certificate_image']['alt']); ?>"
                          class="certificate-display-image">
                      </div>
                    <?php endif; ?>

                    <!-- Certificate Information -->
                    <div class="certificate-info bg-sky-50 p-4 pb-6">
                      <?php if ($item['certificate_no']): ?>
                        <div class="certificate_no h3 text-grey-1 tracking-[-0.48px] font-semibold">
                          <?php echo esc_html($item['certificate_no']); ?>
                        </div>
                      <?php endif; ?>

                      <?php if ($item['certificate_date']): ?>
                        <div class="certificate_date body-1 text-grey-3 mb-5 font-normal">
                          <?php echo esc_html($item['certificate_date']); ?>
                        </div>
                      <?php endif; ?>

                      <!-- View Certificate Button -->
                      <?php if ($item['certificate_popup_image']): ?>
                        <div class="certificate_link">
                          <div class="view-certificate-btn flex items-center gap-2 text-primary text-base font-semibold tracking-[0.16px] cursor-pointer"
                            data-certificate-image="<?php echo esc_url($item['certificate_popup_image']['url']); ?>"
                            data-certificate-alt="<?php echo esc_attr($item['certificate_popup_image']['alt'] ?: $item['certificate_no']); ?>"
                            aria-label="View <?php echo esc_attr($item['certificate_no'] ?: 'certificate'); ?>">
                            <span class="icon">
                              <img src="<?= get_stylesheet_directory_uri(); ?>/assets/images/about/Eye.svg" alt="resin">
                            </span>
                            View Certificate
                          </div>
                        </div>
                      <?php endif; ?>
                    </div>
                  </div>
                </div>
              <?php endforeach; ?>
            </div>
          </div>

          <!-- Slider Navigation & Pagination -->
          <div class="mt-3 lg:hidden flex justify-center items-center gap-4 mb-6">
            <div class="swiper-btn-prev-pagination swiper-btn-prev">
              <svg xmlns="http://www.w3.org/2000/svg" width="9" height="7" viewBox="0 0 9 7" fill="none">
                <path d="M7.92 3.18c.24 0 .44.2.44.45s-.2.44-.44.44H1.67l2.13 2.13a.44.44 0 01-.63.63L.59 4.26a.9.9 0 010-1.26l2.58-2.57a.44.44 0 01.63.63L1.67 3.18h6.25z" fill="#DA000E" />
              </svg>
            </div>

            <div class="swiper-pagination-custom text-primary text-xs font-medium !w-4 !h-4"></div>

            <div class="swiper-btn-next-pagination swiper-btn-next">
              <svg xmlns="http://www.w3.org/2000/svg" width="9" height="7" viewBox="0 0 9 7" fill="none">
                <path d="M1.16 3.18a.44.44 0 000 .89h6.25L5.29 6.2a.44.44 0 10.63.63l2.58-2.58a.9.9 0 000-1.26L5.92.43a.44.44 0 10-.63.63l2.13 2.13H1.16z" fill="#DA000E" />
              </svg>
            </div>
          </div>
        </div><!-- /.certificate-slider-container -->
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>