<?php

/**
 * Global Banner Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (textarea)
 * - description (wysiwyg)
 * - inner_banner_image (image)
 */

$title = get_sub_field('title') ?: '';
$description = get_sub_field('description') ?: '';
$inner_banner_image = get_sub_field('inner_banner_image') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $description || $inner_banner_image)): ?>
  <section class="global_banner_block section-triger" data-load="eager">
    <div class="container-fluid">

      <div class="flex gap-2 flex-col text-center mb-6 lg:mb-9">
        <?php if ($title): ?>
          <h2 class="text-primary fade-text"><?php echo esc_html($title); ?></h2>
        <?php endif; ?>

        <?php if ($description): ?>
          <div class="banner-description max-w-6xl mx-auto prose prose-p:text-base prose-p:leading-[22px] lg:prose-p:text-[18px] lg:prose-p:leading-[25px] prose-p:font-normal prose-p:text-grey-2 anim-uni-in-up">
            <?php echo wp_kses_post($description); ?>
          </div>
        <?php endif; ?>
      </div>

      <?php if ($inner_banner_image): ?>
        <div class="inner_banner_image-wrapper  relative bottom-right overflow-hidden">
          <?php if (function_exists('resplast_optimized_image')): ?>
            <?php echo resplast_optimized_image($inner_banner_image['ID'], 'large', [
              'class' => 'inner_banner_image-image size-full object-cover rounded-[20px] lg:rounded-[40px] myimg',
              'alt' => $inner_banner_image['alt'] ?: '',
              'lazy' => true
            ]); ?>
          <?php else: ?>
            <img src="<?php echo esc_url($inner_banner_image['url']); ?>"
              alt="<?php echo esc_attr($inner_banner_image['alt']); ?>"
              class="inner_banner_image-image myimg">
          <?php endif; ?>
          <div class="uncover">
            <div class="uncover_slice"></div>
            <div class="uncover_slice"></div>
            <div class="uncover_slice"></div>
          </div>
        </div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>