<?php

/**
 * Service Banner Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 */


// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block): ?>
  <section class="service_banner_block py-12">
    <div class="container mx-auto px-4">


    </div>
  </section>
<?php endif; ?>
