<?php

/**
 * Testimonials Block (Hear from our people) Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (text)
 * - description (textarea)
 * - testimonials (repeater)
 *   - quote (textarea)
 *   - name (text)
 *   - position (text)
 *   - image (image)
 * - slider_settings (group)
 *   - autoplay (true_false)
 *   - autoplay_delay (number)
 *   - show_navigation (true_false)
 */

$title = get_sub_field('title') ?: '';
$description = get_sub_field('description') ?: '';
$testimonials = get_sub_field('testimonials') ?: '';
$slider_settings = get_sub_field('slider_settings') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $description || $testimonials)): ?>
  <section class="testimonials_block py-12">
    <div class="container mx-auto px-4">

      <?php if ($title): ?>
        <h2 class="text-3xl font-bold mb-6"><?php echo esc_html($title); ?></h2>
      <?php endif; ?>

      <?php if ($description): ?>
        <div class="description-text"><?php echo esc_html($description); ?></div>
      <?php endif; ?>

      <?php if ($testimonials): ?>
        <div class="testimonials-grid">
          <?php foreach ($testimonials as $item): ?>
            <div class="testimonials-item">
              <?php if ($item['quote']): ?>
                <div class="quote"><?php echo esc_html($item['quote']); ?></div>
              <?php endif; ?>
              <?php if ($item['name']): ?>
                <div class="name"><?php echo esc_html($item['name']); ?></div>
              <?php endif; ?>
              <?php if ($item['position']): ?>
                <div class="position"><?php echo esc_html($item['position']); ?></div>
              <?php endif; ?>
              <?php if ($item['image']): ?>
                <img src="<?php echo esc_url($item['image']['url']); ?>" alt="<?php echo esc_attr($item['image']['alt']); ?>">
              <?php endif; ?>
            </div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>

      <?php if ($slider_settings): ?>
        <div class="slider_settings-field"><?php echo esc_html($slider_settings); ?></div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
