<?php

/**
 * Accordion Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - hide_block (true_false)
 * - title (text)
 * - description (wysiwyg)
 * - accordion_items (repeater)
 *   - heading (text)
 *   - content (textarea)
 *   - accordion_image (image)
 */

$title = get_sub_field('title') ?: '';
$description = get_sub_field('description') ?: '';
$accordion_items = get_sub_field('accordion_items') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($title || $description || $accordion_items)): ?>
  <section class="accordion_block py-12">
    <div class="container mx-auto px-4">

      <?php if ($title): ?>
        <h2 class="text-3xl font-bold mb-6"><?php echo esc_html($title); ?></h2>
      <?php endif; ?>

      <?php if ($description): ?>
        <div class="description-content prose max-w-none">
          <?php echo wp_kses_post($description); ?>
        </div>
      <?php endif; ?>

      <?php if ($accordion_items): ?>
        <div class="accordion_items-grid">
          <?php foreach ($accordion_items as $item): ?>
            <div class="accordion_items-item">
              <?php if ($item['heading']): ?>
                <div class="heading"><?php echo esc_html($item['heading']); ?></div>
              <?php endif; ?>
              <?php if ($item['content']): ?>
                <div class="content"><?php echo esc_html($item['content']); ?></div>
              <?php endif; ?>
              <?php if ($item['accordion_image']): ?>
                <img src="<?php echo esc_url($item['accordion_image']['url']); ?>" alt="<?php echo esc_attr($item['accordion_image']['alt']); ?>">
              <?php endif; ?>
            </div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
