<?php

/**
 * Privacy Accordion Block Template
 * Auto-generated by ACF Block Generator
 *
 * ACF Fields:
 * - acc (repeater)
 *   - title (text)
 *   - content (wysiwyg)
 */

$acc = get_sub_field('acc') ?: '';

// Include hide block functionality
include locate_template('templates/blocks/hide_block.php', false, false);

if (!$hide_block && ($acc)): ?>
  <section class="privacy_accordion_block py-12">
    <div class="container mx-auto px-4">

      <?php if ($acc): ?>
        <div class="acc-grid">
          <?php foreach ($acc as $item): ?>
            <div class="acc-item">
              <?php if ($item['title']): ?>
                <div class="title"><?php echo esc_html($item['title']); ?></div>
              <?php endif; ?>
              <?php if ($item['content']): ?>
                <div class="content"><?php echo esc_html($item['content']); ?></div>
              <?php endif; ?>
            </div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>


    </div>
  </section>
<?php endif; ?>
